# Generated by Django 3.1.6 on 2021-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('account', models.IntegerField(max_length=50)),
                ('balance', models.IntegerField(max_length=50)),
            ],
        ),
    ]
