# Generated by Django 3.1.6 on 2021-02-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210209_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='', max_length=250)),
                ('s_account', models.CharField(max_length=250)),
                ('amount_transfer', models.IntegerField()),
                ('r_name', models.CharField(default='', max_length=250)),
                ('r_account', models.CharField(max_length=250)),
                ('r_balance', models.IntegerField()),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
